name: 'Issue States'
description: 'Close or reopen issues when they are moved to a project column'
author: 'Armin Sebastian'
inputs:
  github-token:
    description: 'GitHub access token'
    default: '${{ github.token }}'
  open-issue-columns:
    description: 'Reopen issues that are moved to these project columns, value must be a comma separated list of project columns'
    default: ''
  closed-issue-columns:
    description: 'Close issues that are moved to these project columns, value must be a comma separated list of project columns'
    default: 'Closed, Done'
  log-output:
    description: 'Log output parameters, value must be either `true` or `false`'
    default: false
outputs:
  issues:
    description: 'Issues that have been either closed or reopened, value is a JSON string'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'box'
  color: 'red'
